

;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2021 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : E0A6A7ECBB46D743B46D6D3926EE315E874F4E29335E7F534F574D16A7575055
; Input MD5    : E360E002B709F6D0D16F1BFF3F732023
; Input CRC32  : 40EE6EC7

; File Name   : /home/julesimf/source/HCC86/kernel86/dbg/Fib
; Format      : ELF64 for x86-64 (Executable)
; Imagebase   : 400000
;

                .686p
                .mmx
                .model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
LOAD            segment byte public 'CODE' use64
                assume cs:LOAD
                ;org 400000h
                assume es:nothing, ss:nothing, ds:LOAD, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================


                public start
start           proc near
                push    0Ah
                mov     rax, 1
                mov     rdx, 1          ; count
                mov     rsi, rsp        ; buf
                mov     rdi, 1          ; fd
                syscall                 ; LINUX - sys_write
                pop     rax
                retn
start           endp

; ---------------------------------------------------------------------------
                mov     r8, [rsp+8]
                cmp     r8, 0
                jge     short loc_400049
                push    2Dh ; '-'
                mov     rax, 1
                mov     rdx, 1
                mov     rsi, rsp
                mov     rdi, 1
                syscall                 ; LINUX - sys_write
                pop     rax
                neg     r8

loc_400049:                             ; CODE XREF: LOAD:0000000000400027↑j
                xor     r9, r9
                mov     rbx, 0Ah
                mov     rax, r8

loc_400056:                             ; CODE XREF: LOAD:0000000000400067↓j
                xor     rdx, rdx
                idiv    rbx
                add     rdx, 30h ; '0'
                push    rdx
                inc     r9
                test    rax, rax
                jnz     short loc_400056

loc_400069:                             ; CODE XREF: LOAD:000000000040008A↓j
                mov     rdi, 1
                mov     rdx, 1
                mov     rsi, rsp
                mov     rax, 1
                syscall                 ; LINUX - sys_write
                pop     rax
                dec     r9
                test    r9, r9
                jnz     short loc_400069
                xor     rax, rax
                retn
; ---------------------------------------------------------------------------
                dq 0C749DB3148C9314Dh, 3148530000000AC0h, 48E68948FF3148C0h
                dq 50F00000001C2C7h, 2DFF8348243C8B48h, 0CD0774C9854D1575h
                dq 0C749C3C031485804h, 48CFEB00000001C1h, 0FF8348137C30FF83h
                dq 4930EF83480D7F39h, 0B6EBFB0148D8AF0Fh, 854D0D750AFF8348h
                dq 4858DBF7480374C9h, 31485804CDC3D889h
                db 0C0h, 0C3h

; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_400102      proc near

arg_0           = qword ptr  10h

                push    rbp
                mov     rbp, rsp
                mov     rbx, [rbp+arg_0]
                mov     rcx, 0
                cmp     rbx, rcx
                setz    bl
                movzx   rbx, bl
                test    rbx, rbx
                jz      near ptr 40025Ah
                mov     rbx, 0
                mov     rax, rbx
                pop     rbp
                retn
sub_400102      endp

; ---------------------------------------------------------------------------
                db 0E9h, 34h, 1, 2 dup(0)
                dq 48000000109D8B48h, 394800000001C1C7h, 0DBB60F48C3940FCBh
                dq 165840FDB8548h, 1C3C74800h, 166E9C35DD88948h, 109D8B480000h
                dq 108D8B485300h, 1C6C74800h, 0FDE851F12948h, 8C4814800h
                dq 48CB0148C189485Bh, 8948C35DC35DD889h, 8EC8148E5h, 0C389480000008BE8h
                dq 48FFFFFFF89D8B48h, 0E853FFFFFFF89D8Bh, 8C48148000000FDh
                dq 0E853C38948000000h, 8C4814800000019h, 0C748C38948000000h
                dq 50F0000003CC0h
                db 7 dup(0)
LOAD            ends


                end start
